title: kai的博客 #站点标题
description: | # 头像背后的信息（html格式），<br/>代表换行
作为一个鬼才！<br/>
  初三党<br/>
  人生一场 别去分清真相<br/>
  kai.52yi.vip<br/>
  <a href="mailto:2398954487@qq.com">
    <i class="fas fa-envelope"></i>
  </a>
  <a href="https://github.com/2398954487">
    <i class="fab fa-github"></i>
  </a>
  <a href="https://zhidao.baidu.com/usercenter?uid=4f3e4069236f25705e79076e
    <i class="fas fa-chart-bar"></i>
  </a>
  <a href="https://vjudge.net/user/kaiERROr">
    <i class="fas fa-smile"></i>
  </a>
  <a href="<"2398954487">
    <i class="fab fa-qq"></i>
  </a>
  </a>
  <iframe
    src="https://music.163.com/outchain/player?type=2&id=427609888&auto=0&height=32"
    width=100%
    height=52
    frameborder="no"
    border="0"
    marginwidth="0"
    marginheight="0"
  ></iframe>
url: https://kai.52yi.vip # 你的域名，例如https://wu-kan.github.io
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。

jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
  default:
    body:
      theme-base: theme-base-0d # 可选的值08~0f，见<https://github.com/poole/lanyon>
      layout-reverse: false # 开启后sidebar在右边，反之左边
      sidebar-overlay: false # 开启后正文不随sidebar移动而移动
    append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章<https://wu-kan.cn/_posts/2019-01-18-基于Jekyll搭建个人博客/>
      - | #一些页面优化标签，看不懂可跳过
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1"
        />
        <meta
          http-equiv="content-type"
          content="text/html; charset=utf-8"
        />
        <link
          rel="alternate"
          href="/feed.xml"
          title="RSS"
          type="application/rss+xml"
        />
      - | # 网站小图标，可换成你自己的图片，改href中的部分即可
        <link
          rel="apple-touch-icon-precomposed"
          href="https://s1.ax1x.com/2020/03/21/8W7sDU.jpg"
        />
        <link
          rel="shortcut
          icon"
          href="https://s1.ax1x.com/2020/03/21/8W7sDU.jpg"
        />
      - | # 来自lanyon的页面样式，不要改
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/combine/gh/poole/lanyon@ac85a3115c094b3e6cb92cc41771e98b443f6c5d/public/css/poole.min.css,gh/poole/lanyon@ac85a3115c094b3e6cb92cc41771e98b443f6c5d/public/css/lanyon.min.css"
        />
      - | #对于lanyon侧边栏按钮的一些补丁，Hide the sidebar checkbox that we toggle with `.sidebar-toggle`；建议不要改
        <style>
          .sidebar-checkbox {
            display: none;
          }
          .sidebar-toggle {
            position: fixed;
          }
          .sidebar-toggle:before,
          .sidebar-toggle:active:before,
          #sidebar-checkbox:focus~.sidebar-toggle:before,
          #sidebar-checkbox:checked~.sidebar-toggle:before {
            background-image: none;
          }
        </style>
      - | # 引入fontawesome图标样式
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"
        />
      - | # 引入live2d看板娘！不需要可以把这一项都删掉
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"
        />
        <script
          async="async"
          src="https://cdn.jsdelivr.net/combine/gh/Dreamer-Paul/Pio@2.4/static/l2d.min.js,gh/Dreamer-Paul/Pio@2.4/static/pio.min.js"
          onload='
            if (screen.width > screen.height)
            {
              let pio_container = document.createElement("div");
              pio_container.classList.add("pio-container");
              pio_container.classList.add("right");
              pio_container.style.bottom = "-2rem";
              pio_container.style.zIndex = "1";
              document.body.insertAdjacentElement("beforeend", pio_container);
              let pio_action = document.createElement("div");
              pio_action.classList.add("pio-action");
              pio_container.insertAdjacentElement("beforeend", pio_action);
              let pio_canvas = document.createElement("canvas");
              pio_canvas.id = "pio";
              pio_canvas.style.width = "14rem";
              pio_canvas.width = "600";
              pio_canvas.height = "800";
              pio_container.insertAdjacentElement("beforeend", pio_canvas);
              let pio = new Paul_Pio({
                "mode": "fixed",
                "hidden": true,
                "content": {
                  "link": ["https://inforest.xzzxz.cn/comments/"],
                  "skin": ["要换成我的朋友吗？", "让她放个假吧~"],
                  "custom": [{
                    "selector": "a",
                    "type": "link",
                  }, {
                    "selector": ".sidebar-toggle",
                    "text": "打开侧边栏叭~"
                  }, {
                    "selector": ".effect-info",
                    "text": "哇，你发现了什么！"
                  }, {
                    "selector": "#sidebar-search-input",
                    "text": "想搜索什么呢？很多干货哦！"
                  }, {
                    "selector": "#toc",
                    "text": "这是目录~"
                  }, {
                    "selector": ".page-title",
                    "text": "这是标题~"
                  }, {
                    "selector": ".v",
                    "text": "评论没有审核，要对自己的发言负责哦~"
                  }]
                },
                "model": [
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/33/model.2018.bls-winter.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/platelet-2/model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/xiaomai/xiaomai.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/mashiro/seifuku.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/seele/model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/Violet/14.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/Kobayaxi/Kobayaxi.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/mikoto/mikoto.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/uiharu/uiharu.model.json"]
              });
            }'
        ></script>
      - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js
        <script
          src='https://zz.bdstatic.com/linksubmit/push.js'
          defer="defer"
        ></script>
      - | # 网站背景图片，分竖屏、宽屏；改链接即可，不想用可以把这一项全删掉；要换壁纸图片的话可把url内的部分换成你自己的，比如你放在/assets/image/background.jpg，那就改成url(/assets/image/background.jpg)
        <style>
          .wrap {
            min-height: 100vh;
            display: inline-block;
            background-size: 100vw auto;
            background-position: center top;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-image: url(https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1586407291184&di=a05cecc91f6b48a1afbaba1580d52a9a&imgtype=0&src=http%3A%2F%2Fpics4.baidu.com%2Ffeed%2F9c16fdfaaf51f3de97d95c06da4ca0193b297995.jpeg%3Ftoken%3D1710364227d586453fe2d3bdaf56bafe%26s%3DF69531C4D4318BD420D0E4130300E0CB);
          }
          @media (min-aspect-ratio: 2400/1850) {
            .wrap {
              background-image: url(https://s1.ax1x.com/2020/04/08/GRZkCT.jpg);
            }
          }
        </style>
      - | # 网站字体
        <style>
          html,
          h1,
          h2,
          h3,
          h4,
          h5,
          h6,
          .sidebar {
            font-family: Menlo, Monaco, "Courier New", Microsoft JhengHei, monospace;
          }
        </style>
      - | # 侧边栏头像效果
        <style>
          .effect {
            margin: 1rem;
            perspective: 900px;
          }
          .effect-info {
            text-align: center;
            backface-visibility: hidden;
            position: absolute;
            top: 0;
            transform-style: preserve-3d;
          }
          .effect-img {
            z-index: 11;
            width: 100%;
            height: 100%;
            position: relative;
            transition: all 0.5s ease-in-out;
          }
          .effect-img:before {
            position: absolute;
            display: block;
          }
          .effect-right_to_left .effect-img {
            transform-origin: 0% 50%;
          }
          .effect-right_to_left:hover .effect-img {
            transform: rotate3d(0, 1, 0, -180deg);
          }
        </style>
      - | # 彩虹滚动条，仅对Chrome系浏览器生效
        <style>
          ::-webkit-scrollbar {
            width: 4px;
            height: 4px;
          }
          ::-webkit-scrollbar-thumb {
            background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
          }
        </style>
      - | # 如果你会CSS的话，在这里自定义你的页面样式吧~
        <style>
          img {
            display: inline-block;
            margin: 0;
          }
        </style>
    sidebar: # 此配置项下是一些关于侧边栏的配置
      disable: false # 是否不显示sidebar
      avatar: # 侧边栏显示的头像
        enable: true
        img: https://s1.ax1x.com/2020/04/06/Gs51OS.jpg # 头像的地址
      nav: # 导航部分的内容，你也可以自己增加文字、图标（来自fontawesome）和对应的链接
        - title: '<i class="fas fa-home fa-fw"></i> 首页'
          href: /
        - title: '<i class="fas fa-comments fa-fw"></i> 留言'
          href: /comments/
        - title: '<i class="fas fa-tags fa-fw"></i> 标签'
          href: /tags/
        - title: '<i class="fas fa-archive fa-fw"></i> 归档'
          href: /archive/
        - title: '<i class="fas fa-coffee fa-fw"></i> 打赏'
          href: /merger/
        - title: '2020/4/9更新 v1.1.2'
          href: /
      simple_jekyll_search: # 侧边栏的全站搜索
        enable: true
        full_text_search: false # 可能导致缓慢的搜索和加载
        alert: | # 如果看不懂就不改
          <input
            id="sidebar-search-input"
            placeholder="搜索博文"
            style="background: none;border: none;color: #fff;width: 100%;"/>
          <ol
            id="sidebar-search-results-container"
            style="overflow: auto auto;max-height:50vh;"
          ></ol>
          <script
            src='https://cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js'
            async='async'
            onload='
              SimpleJekyllSearch({
                json: "/assets/simple-jekyll-search/search.json",
                searchInput: document.getElementById("sidebar-search-input"),
                resultsContainer: document.getElementById("sidebar-search-results-container"),
                searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                limit: 999,
                fuzzy: true
              })'
          ></script>
      append_to_sidebar:
        - | # 目录插件，如果看不懂就不改
          <aside style="overflow: auto auto;max-height:50vh;" id="toc">
            目录
          </aside>
          <script
            defer='defer'
            src='https://cdn.jsdelivr.net/npm/html-contents/html-contents.min.js'
            onload="htmlContents('#toc', {listType: 'o', filter: function(arr) {return !arr.matches('.masthead-title')}})"
          ></script>
        - | # 运行时间，可将倒数第三行的时间改成你自己的建站时间，格式仿照上面的；不需要的话可以把这一项都删掉
          <div>
            <i class="fas fa-cog fa-spin fa-fw"></i>
            <span id="run_time_day">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>天
            <span id="run_time_hour">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>时
            <span id="run_time_minute">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>分
            <span id="run_time_second">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>秒
            <script>
              setInterval(function (BirthDay) {
                function setzero(i) {
                  if (i < 10) return "0" + i;
                  return i;
                }
                BirthDay = new Date(BirthDay);
                today = new Date();
                timeold = (today.getTime() - BirthDay.getTime());
                sectimeold = timeold / 1000;
                secondsold = Math.floor(sectimeold);
                msPerDay = 24 * 60 * 60 * 1000;
                e_daysold = timeold / msPerDay;
                daysold = Math.floor(e_daysold);
                e_hrsold = (e_daysold - daysold) * 24;
                hrsold = Math.floor(e_hrsold);
                e_minsold = (e_hrsold - hrsold) * 60;
                minsold = Math.floor((e_hrsold - hrsold) * 60);
                seconds = Math.floor((e_minsold - minsold) * 60);
                document.getElementById("run_time_day").innerHTML = daysold;
                document.getElementById("run_time_hour").innerHTML = setzero(hrsold);
                document.getElementById("run_time_minute").innerHTML = setzero(minsold);
                document.getElementById("run_time_second").innerHTML = setzero(seconds);
              }, 1000, "2020/3/17 8:23:28") // 这是我第一篇CSDN博客的时间
            </script>
          </div>
        - | # 不蒜子页面统计，看不懂可不改
          <div>
            <div>
              <i class="fas fa-eye fa-fw"></i>
              <span id="busuanzi_value_page_pv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>次
            </div>
            <div>
              <i class="fas fa-paw fa-fw"></i>
              <span id="busuanzi_value_site_pv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>枚
            </div>
            <div>
              <i class="fas fa-user-friends fa-fw"></i>
              <span id="busuanzi_value_site_uv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>人
            </div>
            <script
              src='https://cdn.jsdelivr.net/npm/busuanzi'
              async='async'
            ></script>
          </div>
        - | # Copyright声明
          <div>
            <i class="fas fa-copyright fa-fw"></i>
            2017-2020 KaI
          </div>
        - | # 觉得我的主题好用的话，让更多的人知道它吧！
          <div>
            <i class="fas fa-thumbs-up fa-fw"></i>
             友链栏<br/>
              <a href="https://github.com/wu-kan">
               jekyll-theme-Wuk</br>
              <a href="http://www.1xie.xyz/">
               筱谢博客
            </a>
          </div>
      wordcount: # 全站字数统计
        enable: true # 本地调试时建议关闭，非常影响站点生成速度（所需时间与博文数量的平方成正比）
        alert: <i class="fas fa-user-edit fa-fw"></i>
        kilo: 千
        unit: 字
  page:
    masthead: # 显示顶栏
      enable: true
    append_before:
      - | # 代码块背景透明（否则mermaid受影响），且代码块超过半屏的时候自动折叠
        <style>
          pre {
            max-height: 50vh;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0);
          }
        </style>
      - | # 增加宽屏下的显示内容，黄 金 分 割 比
        <style>
          @media (min-width: 56em) {
            .container {
              max-width: 61.8%;
            }
          }
        </style>
      - | # 给文章加上白色背景，防止被背景影响阅读；同时加上加载动画
        <style>
          .masthead,
          .container.content {
            padding-top: 1rem;
            padding-bottom: 1rem;
            box-shadow: 0 0 .75rem rgba(0, 0, 0, 0.1);
            background-color: rgba(255, 255, 255, 0.9);
            animation: animationAppear 2s;
          }
          @keyframes animationAppear {
            0%,
            33% {
              opacity: 0;
            }
            100% {}
          }
        </style>
      - | # 使文章支持Katex数学公式渲染，行内公式用$...$括起来，行内公式用$$..$$括起来
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css"
        />
        <script
          src="https://cdn.jsdelivr.net/combine/npm/katex/dist/katex.min.js,npm/katex/dist/contrib/mathtex-script-type.min.js,npm/katex/dist/contrib/auto-render.min.js"
          defer="defer"
          onload='renderMathInElement(document.body, { delimiters: [{ left: "$", right: "$", display: false }] })'
        ></script>
      - | # mermaid
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.css"
        />
        <script
          src="https://cdn.jsdelivr.net/
